matrix:
  include:
    - os: osx
      env: ACTION=lint
    - os: osx
      env: ACTION=iOS
    - os: osx
      env: ACTION=OSX
    - os: osx
      env: ACTION=tvOS
    - os: osx
      env: ACTION=carthage
    - os: osx
      env: ACTION=coverage
    - os: osx
      env: ACTION=oss-osx

language: objective-c
osx_image: xcode7.3

script:
  - make install-$ACTION && make test-$ACTION
